language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-test-dev -y
jobs:
  include:
    - stage: helloworld
      script:
        - cd hw1
        - cmake . -DBUILD_TESTING=ON
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target package
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - curl -T hw1/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usanblch:$BINTRAY_API_KEY "https://api.bintray.com/content/sanblch/homework/homework/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    - stage: ip_filter
      script:
        - cd hw2
        - cmake . -DBUILD_TESTING=ON 
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target package
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - curl -T hw2/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usanblch:$BINTRAY_API_KEY "https://api.bintray.com/content/sanblch/homework/homework/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
