language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-test-dev -y
jobs:
  include:
    - stage: matrix
      script:
        - cd hw5
        - cmake .
        - cmake --build .
        - cmake --build . --target package
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - curl -T matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usanblch:$BINTRAY_API_KEY "https://api.bintray.com/content/sanblch/homework/homework/$TRAVIS_BUILD_NUMBER/matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    - stage: print_ip
      script:
        - cd hw4
        - cmake .
        - cmake --build .
        - cmake --build . --target package
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usanblch:$BINTRAY_API_KEY "https://api.bintray.com/content/sanblch/homework/homework/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    - stage: allocator
      script:
        - cd hw3
        - cmake .
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target package
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usanblch:$BINTRAY_API_KEY "https://api.bintray.com/content/sanblch/homework/homework/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    - stage: ip_filter
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      script:
        - eval "${MATRIX_EVAL}"
        - cd hw2
        - cmake . -DBUILD_TESTING=ON 
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target package
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usanblch:$BINTRAY_API_KEY "https://api.bintray.com/content/sanblch/homework/homework/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    - stage: helloworld
      script:
        - cd hw1
        - cmake . -DBUILD_TESTING=ON
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target package
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usanblch:$BINTRAY_API_KEY "https://api.bintray.com/content/sanblch/homework/homework/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
